skip_branch_with_pr: true

environment:
  MODE: test
  PYTHON_VERSION: C:\Miniconda36-x64
  NUMPY_VERSION: numpy<1.15
  TF_VERSION: tensorflow
  NENGO_VERSION: nengo

  matrix:
    - MODE: test # default build
    # - MODE: examples  # TODO: some problem with nbval on windows (timeout)
    - NENGO_VERSION: git+https://github.com/nengo/nengo.git
      TF_VERSION: tensorflow --pre
    - NENGO_VERSION: nengo==2.7.0
      TF_VERSION: tensorflow==1.4.0
      NUMPY_VERSION: numpy==1.12.1
      PYTHON_VERSION: C:\Miniconda35-x64

init:
  - set PATH=%PYTHON_VERSION%;%PYTHON_VERSION%\\Scripts;%PATH%

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - if %MODE% == examples (
      conda install pandoc jupyter &
      pip install -e .[tests,docs]
    ) else (
      pip install -e .[tests]
    )
  - pip install %TF_VERSION%
  - pip install %NENGO_VERSION%
  - pip uninstall -y numpy
  - conda install "%NUMPY_VERSION%"
  - conda list -e
  - pip freeze

build: false  # Not a C# project

test_script:
  - if %MODE% == examples (
      py.test -v --durations 20 --nbval-lax docs/examples
    ) else (
      py.test -n 2 --pyargs nengo && py.test -n 2 --durations 20 nengo_dl
    )
