skip_branch_with_pr: true

environment:
  MODE: test
  PYTHON_VERSION: C:\Miniconda35-x64
  NENGO_DL_TEST_PRECISION: 32
  NENGO_DL_TEST_UNROLL: 1
  NUMPY_VERSION: numpy
  TF_VERSION: tensorflow
  NENGO_VERSION: nengo

  matrix:
    - MODE: test # default build
    # - MODE: examples  # TODO: some problem with nbval on windows (timeout)
    - TF_VERSION: tf-nightly
      NENGO_VERSION: git+https://github.com/nengo/nengo.git
    - NUMPY_VERSION: numpy==1.11.0
      TF_VERSION: tensorflow==1.3.0
      NENGO_VERSION: nengo==2.5.0

init:
  - set PATH=%PYTHON_VERSION%;%PYTHON_VERSION%\\Scripts;%PATH%

install:
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install %NUMPY_VERSION% matplotlib
  - pip install %TF_VERSION%
  - conda install --force html5lib  # fixes a bug related to tensorflow and pip
  - pip install %NENGO_VERSION%
  - pip install -r requirements-test.txt
  - if %MODE% == examples (
      conda install pandoc jupyter &
      pip install -r requirements-docs.txt
    )
  - pip install -e .
  - conda list -e
  - pip freeze

build: false  # Not a C# project

test_script:
  - if %MODE% == examples (
      py.test -v --durations 20 --nbval-lax docs/examples
    ) else (
      py.test -n 2 --pyargs nengo && py.test -n 2 --durations 20 nengo_dl
    )
